name: Publish - Automate your tenant with PowerShell and Azure Functions

on: 
  workflow_dispatch:
  push:
    paths: 
    - 'Automate your tenant with PowerShell and Azure Functions/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'Automate your tenant with PowerShell and Azure Functions'
      out_folder: 'Automate-your-tenant-with-PowerShell-and-Azure-Functions'
