name: Publish - Coding in the Cloud with GitHub Codespaces
on: 
  workflow_dispatch
env:
  TALK_FOLDER: 'Coding in the Cloud with GitHub Codespaces'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Coding in the Cloud with GitHub Codespaces'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Build
        run: slidev build --out './dist/Coding in the Cloud with GitHub Codespaces'
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
