name: Publish - Coding in the Cloud with GitHub Codespaces
on: 
  workflow_dispatch:
  push:
    paths: 
    - 'Coding in the Cloud with GitHub Codespaces/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'Coding in the Cloud with GitHub Codespaces'
      out_folder: 'Coding-in-the-Cloud-with-GitHub-Codespaces'
