name: Publish - GIT Up & Go
on: 
  workflow_dispatch:
  push:
    paths: 
    - 'GIT Up and Go/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'GIT Up and Go'
      out_folder: 'git-up-and-go'