name: Publish - How to Use Auth0 and .NET 8 to log in from any device, even your toaster
on: 
  workflow_dispatch:
  push:
    paths: 
    - 'How to Use Auth0 and .NET 8 to log in from any device, even your toaster/**'
env:
  ROOT_FOLDER: 'presentations'
  TALK_FOLDER: 'How to Use Auth0 and .NET 8 to log in from any device, even your toaster'
  OUT_FOLDER: 'How-to-Use-Auth0-and-NET-8-to-log-in-from-any-device'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'GIT Up and Go'
      out_folder: 'git-up-and-go'
