name: Publish - Kicking some Ass with PowerShell in VSCode
on: 
  workflow_dispatch:
  push:
    paths: 
    - 'Kicking some Ass with Powershell in VSCode/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'Kicking some Ass with Powershell in VSCode'
      out_folder: 'Kicking-some-Ass-with-Powershell-in-VSCode'
