name: Publish - Microsoft Teams Meeting extensions
on: 
  workflow_dispatch:
  push:
    paths: 
    - 'Microsoft Teams Meeting extensions/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'Microsoft Teams Meeting extensions'
      out_folder: 'Microsoft-Teams-Meeting-extensions'