name: Publish - More Human Than Human - Bringing Digital Humans to Life with Azure AI

on: 
  workflow_dispatch:
  push:
    paths: 
      - 'More Human Than Human - Bringing Digital Humans to Life with Azure AI/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'More Human Than Human Bringing Digital Humans to Life with Azure AI'
      out_folder: 'More-Human-Than-Human-Bringing-Digital-Humans-to-Life-with-Azure-AI'