name: Publish - Public Speaking is not only for events
on: 
  workflow_dispatch:
  push:
    paths: 
    - 'Public Speaking is not only for events/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'Public Speaking is not only for events'
      out_folder: 'Public-Speaking-is-not-only-for-events'