name: Publish - The Secret to Living a Better Life with a Second Brain
on: 
  workflow_dispatch:
  push:
    paths: 
    - 'The Secret to Living a Better Life with a Second Brain/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'The Secret to Living a Better Life with a Second Brain'
      out_folder: 'The-Secret-to-Living-a-Better-Life-with-a-Second-Brain'
