name: Publish - Think Small, Win Big - The Unexpected Power of Small Language Models

on:
  workflow_dispatch:
  push:
    paths:
      - 'Think Small Win Big The Unexpected Power of Small Language Models/**'

env:
  ROOT_FOLDER: 'presentations'
  TALK_FOLDER: 'Think Small Win Big The Unexpected Power of Small Language Models'
  OUT_FOLDER: 'Think-Small-Win-Big-The-Unexpected-Power-of-Small-Language-Models'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './${{ env.TALK_FOLDER }}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install @antfu/ni globally
        run: npm install -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: Build Slidev presentation
        run: nr build --base "/${{ github.event.repository.name }}/${{ env.TALK_FOLDER }}" --out "./dist/${{ env.OUT_FOLDER }}"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: './${{ env.TALK_FOLDER }}/dist/${{ env.OUT_FOLDER }}'
          keep_history: true
          jekyll: false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4