name: Publish - Think Small, Win Big - The Unexpected Power of Small Language Models

on: 
  workflow_dispatch:
  push:
    paths: 
      - 'Think Small Win Big The Unexpected Power of Small Language Models/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-presentation.yml
    with:
      talk_folder: 'Think Small Win Big The Unexpected Power of Small Language Models'
      out_folder: 'Think-Small-Win-Big-The-Unexpected-Power-of-Small-Language-Models'